# Generated by Django 4.0.5 on 2022-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=10, null=True)),
                ('age', models.IntegerField(blank=None, default=20, null=True)),
                ('phone', models.CharField(blank=None, max_length=20, null=True)),
                ('pup_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
