# Generated by Django 4.0.5 on 2022-07-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pup_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=None, max_length=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(blank=None, max_length=10, null=True)),
                ('certification_photo', models.ImageField(blank=True, null=True, upload_to='certification/')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
