# Generated by Django 4.0.5 on 2022-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=None, default='호호', max_length=50, null=True)),
                ('view_auth', models.IntegerField(blank=None, default=0, null=True)),
                ('color', models.CharField(blank=None, default='#000000', max_length=10, null=True)),
                ('pup_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
